# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: New York Times Databricks Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      working-directory: src/workflows
      run: |
        pip install -r requirements.txt
    - name: Update jobs workflow
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_USER: ${{ secrets.DATABRICKS_USER }}
        DATABRICKS_JOBID: ${{ secrets.DATABRICKS_JOBID }}
      working-directory: src/workflows
      run: python main.py
